name: Giving Hand Local
values:
  - key: baseUrl
    enabled: true
    value: 'http://localhost:8182/GivingHandProject-1.0-SNAPSHOT'
  - key: password
    enabled: true
    value: ''
  - key: email
    enabled: true
    value: ''
